"""
TSM - Text Similarity Maker
Streamlit pipeline for building VOSviewer-compatible paper networks.
"""
import csv
import hashlib
import io
import json
import os
import uuid
from pathlib import Path
from urllib.parse import urlencode
import numpy as np
import pandas as pd
import streamlit as st
# Page config
st.set_page_config(
    page_title="TSM Text Similarity Maker",
    page_icon=None,
    layout="wide",
)
st.title("TSM - Text Similarity Maker")
st.caption(
    "Built by [Juan Pablo Bascur](https://jpbascur.com) - "
    "Problems? Contact [juanpablobascurcifuentes@gmail.com](mailto:juanpablobascurcifuentes@gmail.com) - "
    "Source: [github.com/jpbascur/text-similarity-maker](https://github.com/jpbascur/text-similarity-maker)"
)
st.markdown(
    "The purpose of this tool is to facilitate the creation of text similarity science maps from a set of papers. "
    "It provides a pipeline with all the necessary files and functions. "
    "All the steps of the pipeline are accessible to the user so they can provide their own files. "
    "It is composed of two parts:\n\n"
    "- **Files** - The inputs and outputs of the functions. Files can be uploaded manually or generated by the functions. "
    "Manage all files in the **Files** panel at the bottom of the page.\n"
    "- **Functions** - Run the pipeline to generate the science map. Each function can be run independently."
)
with st.expander("Demo data", expanded=False):
    st.caption(
        "50 sample papers in RIS format - a common bibliometric export format. "
        "Download the file below, then upload it to **Papers (unformatted)** in the Files panel "
        "at the bottom of the page. Then use **1.1 Format the papers file** to convert it."
    )
    if "_demo_bytes" not in st.session_state:
        st.session_state["_demo_bytes"] = (Path(__file__).parent / "sample_papers.ris").read_bytes()
    st.download_button(
        "Download demo data", st.session_state["_demo_bytes"],
        "sample_papers.ris", mime="text/plain", key="dl_demo",
    )
st.divider()
st.subheader("Functions")
st.caption(
    "The starting point of the pipeline is a file with papers - each entry needs an ID, title, and abstract."
)
# Helpers
def array_to_csv_bytes(arr: np.ndarray, ids: list[str] | None = None) -> bytes:
    buf = io.StringIO()
    if ids is not None:
        for row_id, row in zip(ids, arr):
            buf.write(row_id + "," + ",".join(f"{v:.8f}" for v in row) + "\n")
    else:
        np.savetxt(buf, arr, delimiter=",", fmt="%.8f")
    return buf.getvalue().encode()
def parse_embeddings_csv(data: bytes) -> tuple[np.ndarray, list[str]]:
    """Fast parser for no-header embeddings CSV: id plus 768 numeric columns."""
    try:
        df = pd.read_csv(io.BytesIO(data), header=None)
    except pd.errors.EmptyDataError as exc:
        raise ValueError("The embeddings file is empty.") from exc
    if df.empty:
        raise ValueError("The embeddings file is empty.")
    try:
        ids = df.iloc[:, 0].astype(str).tolist()
        arr = df.iloc[:, 1:].to_numpy(dtype=np.float32)
    except (ValueError, IndexError) as exc:
        raise ValueError(
            "The embeddings file appears to have a header row. "
            "The first row should be data: paper ID followed by embedding values."
        ) from exc
    if arr.ndim != 2 or arr.shape[1] != 768:
        n_dims = arr.shape[1] if arr.ndim == 2 else 0
        raise ValueError(
            f"Expected 768 embedding dimensions per row, got {n_dims}. "
            "This file does not look like a SPECTER2 embeddings file."
        )
    return arr, ids
def parse_edge_csv(data: bytes) -> list[tuple[int, int, float]]:
    """Fast parser for network CSV files with source, target, weight columns."""
    try:
        df = pd.read_csv(io.BytesIO(data), usecols=["source", "target", "weight"])
    except ValueError as exc:
        raise ValueError("The file must have columns: source, target, weight.") from exc
    except pd.errors.EmptyDataError as exc:
        raise ValueError("The network file is empty.") from exc
    return list(
        zip(
            df["source"].to_numpy(dtype=np.int64).tolist(),
            df["target"].to_numpy(dtype=np.int64).tolist(),
            df["weight"].to_numpy(dtype=np.float64).tolist(),
        )
    )
def parse_coords_csv(data: bytes) -> tuple[list[str], np.ndarray]:
    """Fast parser for coordinate CSV files with id, x, y columns."""
    try:
        df = pd.read_csv(io.BytesIO(data), usecols=["id", "x", "y"])
    except ValueError as exc:
        raise ValueError("The file must have columns: id, x, y.") from exc
    except pd.errors.EmptyDataError as exc:
        raise ValueError("The coordinates file is empty.") from exc
    ids = df["id"].astype(str).tolist()
    coords = df[["x", "y"]].to_numpy(dtype=np.float32)
    return ids, coords
def parse_papers_csv(data: bytes) -> list[dict]:
    """Fast parser for formatted papers CSV files."""
    try:
        df = pd.read_csv(io.BytesIO(data), dtype=str, keep_default_na=False)
    except pd.errors.EmptyDataError as exc:
        raise ValueError("The papers file is empty.") from exc
    missing_cols = [c for c in ["id", "title", "abstract"] if c not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing columns: {missing_cols}. The file must have columns: id, title, abstract.")
    return df.to_dict("records")
def uploaded_file_bytes(upload_key: str, file_obj) -> tuple[bytes, str] | None:
    """Return uploaded bytes and a stable signature, or None if already handled."""
    data = file_obj.getvalue()
    digest = hashlib.blake2b(data, digest_size=16).hexdigest()
    signature = f"{file_obj.name}:{len(data)}:{digest}"
    processed_key = f"_processed_{upload_key}"
    if st.session_state.get(processed_key) == signature:
        return None
    st.session_state[processed_key] = signature
    return data, signature
def handle_panel_upload(upload_key: str, slot_key: str):
    """Process a Files panel upload from a Streamlit widget callback."""
    file_obj = st.session_state.get(upload_key)
    if file_obj is None:
        return
    uploaded = uploaded_file_bytes(upload_key, file_obj)
    if uploaded is None:
        return
    raw, _signature = uploaded
    error_key = f"_upload_error_{upload_key}"
    try:
        if slot_key == "raw":
            st.session_state["raw_file"] = (file_obj.name, raw)
            st.session_state.pop("_raw_parsed", None)
            st.session_state.pop("_raw_parsed_key", None)
        elif slot_key == "papers":
            parsed = parse_papers_csv(raw)
            st.session_state["step1_papers"] = parsed
            st.session_state["s1_file"] = (file_obj.name, raw)
            _clear_downstream_papers()
            st.session_state["_dl_papers"] = raw
        elif slot_key == "embeddings":
            arr, ids = parse_embeddings_csv(raw)
            st.session_state["step1_embeddings"] = arr
            st.session_state["step1_embed_ids"] = ids
            _clear_downstream_embeddings()
            st.session_state["_dl_embeddings"] = raw
        elif slot_key == "edges":
            st.session_state["step2_edges"] = parse_edge_csv(raw)
            _clear_downstream_edges()
            st.session_state["_dl_edges"] = raw
        elif slot_key == "network_vos":
            json_str = raw.decode("utf-8")
            data = json.loads(json_str)
            sid = st.session_state["session_id"]
            st.session_state["vos_json_auto"] = json_str
            st.session_state["vos_json_fixed"] = json_str
            st.session_state["vos_json_url_auto"] = _write_static_json(f"{sid}_network_auto.json", data)
            st.session_state["vos_json_url_fixed"] = _write_static_json(f"{sid}_network_fixed.json", data)
        elif slot_key == "coords":
            st.session_state["viz_ids"], st.session_state["viz_coords"] = parse_coords_csv(raw)
            _clear_downstream_coords()
            st.session_state["_dl_coords"] = raw
        elif slot_key == "coords_vos":
            json_str = raw.decode("utf-8")
            data = json.loads(json_str)
            sid = st.session_state["session_id"]
            st.session_state["viz_vos_json"] = json_str
            st.session_state["viz_vos_json_url"] = _write_static_json(f"{sid}_umap.json", data)
        st.session_state.pop(error_key, None)
    except Exception as exc:
        st.session_state[error_key] = str(exc)
def show_array_info(arr: np.ndarray, label: str = "Array"):
    st.caption(f"{label}: {arr.shape[0]} papers -- {arr.shape[1]} dimensions")
def parse_pubmed_export(text: str) -> list[dict]:
    """Parse a PubMed .txt or .nbib export into [{id, title, abstract}]."""
    import re
    records, current, current_tag = [], {}, None
    for line in text.splitlines():
        if re.match(r'^ER\s*-', line):
            if current:
                records.append(current)
            current, current_tag = {}, None
            continue
        m = re.match(r'^([A-Z]+)\s*-\s+(.*)', line)
        if m:
            current_tag = m.group(1)
            val = m.group(2).strip()
            current[current_tag] = (current[current_tag] + " " + val) if current_tag in current else val
        elif line.startswith("      ") and current_tag:
            current[current_tag] += " " + line.strip()
        elif not line.strip():
            if current:
                records.append(current)
            current, current_tag = {}, None
    if current:
        records.append(current)
    return [
        {"id": r["PMID"].strip(), "title": r["TI"].strip(), "abstract": r.get("AB", "").strip()}
        for r in records if "PMID" in r and "TI" in r
    ]
def parse_ris_export(text: str) -> list[dict]:
    """Parse a RIS (.ris) export into [{id, title, abstract}]."""
    import re
    records, current, current_tag = [], {}, None
    for line in text.splitlines():
        if re.match(r'^ER\s*-', line):
            if current:
                records.append(current)
            current, current_tag = {}, None
            continue
        m = re.match(r'^([A-Z][A-Z0-9])\s+-\s+(.*)', line)
        if m:
            current_tag = m.group(1)
            val = m.group(2).strip()
            current[current_tag] = (current[current_tag] + " " + val) if current_tag in current else val
        elif line.startswith("  ") and current_tag:
            current[current_tag] += " " + line.strip()
        elif not line.strip():
            if current:
                records.append(current)
            current, current_tag = {}, None
    if current:
        records.append(current)
    result = []
    for i, r in enumerate(records):
        id_ = r.get("ID") or r.get("AN") or r.get("UT") or r.get("DO") or str(i + 1)
        title = r.get("TI") or r.get("T1", "")
        abstract = r.get("AB") or r.get("N2", "")
        if title:
            result.append({"id": id_.strip(), "title": title.strip(), "abstract": abstract.strip()})
    return result
def parse_bibtex_export(text: str) -> list[dict]:
    """Parse a BibTeX (.bib) export into [{id, title, abstract}]."""
    import re
    result = []
    for entry in re.split(r'(?=@\w+\{)', text):
        key_m = re.match(r'@\w+\{([^,\n]+),', entry)
        if not key_m:
            continue
        key = key_m.group(1).strip()
        def _field(name):
            m = re.search(rf'\b{name}\s*=\s*\{{([^{{}}]*(?:\{{[^{{}}]*\}}[^{{}}]*)*)\}}', entry, re.IGNORECASE)
            if not m:
                m = re.search(rf'\b{name}\s*=\s*"([^"]*)"', entry, re.IGNORECASE)
            if m:
                return re.sub(r'\{([^{}]*)\}', r'\1', m.group(1)).strip()
            return ""
        title = _field("title")
        abstract = _field("abstract")
        if title:
            result.append({"id": key, "title": title, "abstract": abstract})
    return result
def _papers_to_csv_bytes(papers: list[dict]) -> bytes:
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=["id", "title", "abstract"])
    w.writeheader()
    w.writerows(papers)
    return buf.getvalue().encode()
def _edges_to_csv_bytes(edges: list) -> bytes:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["source", "target", "weight"])
    w.writerows(edges)
    return buf.getvalue().encode()
def _coords_to_csv_bytes(ids: list, coords: np.ndarray) -> bytes:
    buf = io.StringIO()
    buf.write("id,x,y\n")
    for pid, (x, y) in zip(ids, coords):
        buf.write(f"{pid},{x:.6f},{y:.6f}\n")
    return buf.getvalue().encode()
def _clear_downstream_papers():
    for key in ["step1_embeddings", "step1_embed_ids", "step2_edges",
                "viz_coords", "viz_ids", "vos_json_auto", "vos_json_fixed",
                "vos_json_url_auto", "vos_json_url_fixed",
                "viz_vos_json", "viz_vos_json_url",
                "_dl_embeddings", "_dl_edges", "_dl_coords"]:
        st.session_state.pop(key, None)
def _clear_downstream_embeddings():
    for key in ["step2_edges", "viz_coords", "viz_ids",
                "vos_json_auto", "vos_json_fixed",
                "vos_json_url_auto", "vos_json_url_fixed",
                "viz_vos_json", "viz_vos_json_url",
                "_dl_embeddings", "_dl_edges", "_dl_coords"]:
        st.session_state.pop(key, None)
def _clear_downstream_edges():
    for key in ["vos_json_auto", "vos_json_fixed",
                "vos_json_url_auto", "vos_json_url_fixed",
                "_dl_edges"]:
        st.session_state.pop(key, None)
def _clear_downstream_coords():
    for key in ["viz_vos_json", "viz_vos_json_url", "_dl_coords"]:
        st.session_state.pop(key, None)
#  session state init 
if "session_id" not in st.session_state:
    st.session_state["session_id"] = uuid.uuid4().hex
if "running" not in st.session_state:
    st.session_state["running"] = False
_is_running = st.session_state["running"]
if _is_running:
    st.warning("A job is already running in this session. Please wait for it to finish.")
try:
    def _read_cgroup_mem():
        try:
            limit = int(Path("/sys/fs/cgroup/memory.max").read_text().strip())
            usage = int(Path("/sys/fs/cgroup/memory.current").read_text().strip())
            return usage, limit
        except Exception:
            pass
        limit = int(Path("/sys/fs/cgroup/memory/memory.limit_in_bytes").read_text().strip())
        usage = int(Path("/sys/fs/cgroup/memory/memory.usage_in_bytes").read_text().strip())
        return usage, limit
    _mem_used, _mem_limit = _read_cgroup_mem()
    _mem_used_gb  = _mem_used  / 1024**3
    _mem_total_gb = _mem_limit / 1024**3
    _mem_free_gb  = (_mem_limit - _mem_used) / 1024**3
    _mem_pct      = _mem_used / _mem_limit * 100
    _mem_caption  = (
        f"Container memory: {_mem_used_gb:.1f} GB used / {_mem_total_gb:.1f} GB total - "
        f"{_mem_free_gb:.1f} GB free ({100 - _mem_pct:.0f}% available). "
        "This tool has limited memory shared across all users. "
        "If memory is low, please wait for it to be released by another user."
    )
except Exception:
    _mem_caption = None
_STATIC_DIR = Path(__file__).parent / "static"
_STATIC_DIR.mkdir(exist_ok=True)
def _public_app_base_url() -> str | None:
    """Return a public base URL if the deployed environment provides one."""
    for env_name in ("PUBLIC_BASE_URL", "APP_BASE_URL", "STREAMLIT_PUBLIC_URL"):
        value = os.environ.get(env_name, "").strip()
        if value:
            return value.rstrip("/")
    space_host = os.environ.get("SPACE_HOST", "").strip()
    if space_host:
        return f"https://{space_host}".rstrip("/")
    space_id = os.environ.get("SPACE_ID", "").strip()
    if space_id:
        slug = space_id.replace("/", "-").lower()
        return f"https://{slug}.hf.space"
    return None
def _write_static_json(filename: str, data: dict) -> str | None:
    path = _STATIC_DIR / filename
    path.write_text(json.dumps(data), encoding="utf-8")
    base_url = _public_app_base_url()
    if not base_url:
        return None
    return f"{base_url}/app/static/{filename}"
def _vosviewer_url(json_url: str | None, **params) -> str | None:
    if not json_url:
        return None
    query = urlencode({"json": json_url, **params})
    return f"https://app.vosviewer.com/?{query}"
# Pipeline steps
with st.expander("1.1  Format the papers file", expanded=False):
    st.caption("**Reads:** Papers (unformatted) - **Saves to Files panel:** Papers (formatted)")
    st.caption(
        "Converts a bibliometric export into a CSV with columns `id`, `title`, and `abstract`. "
        "Supported formats:  \n"
        "**PubMed** (.txt, .nbib) - Send to File, Format: PubMed  \n"
        "**RIS** (.ris) - exported by Scopus, Web of Science, Zotero, Mendeley, EndNote  \n"
        "**BibTeX** (.bib) - exported by Google Scholar, Zotero, most reference managers"
    )
    if "raw_file" not in st.session_state:
        st.info("No unformatted file loaded. Upload **Papers (unformatted)** in the Files panel at the bottom of the page.")
    else:
        raw_fname, raw_bytes = st.session_state["raw_file"]
        st.caption(f"File loaded: {raw_fname}")
        # Parse once and cache; re-parse only when the file changes
        cache_key = ("raw_parsed", raw_fname, len(raw_bytes))
        if st.session_state.get("_raw_parsed_key") != cache_key:
            try:
                text = raw_bytes.decode("utf-8", errors="replace")
                ext = Path(raw_fname).suffix.lower()
                if ext == ".bib":
                    parsed = parse_bibtex_export(text)
                elif ext == ".ris":
                    parsed = parse_ris_export(text)
                else:
                    parsed = parse_pubmed_export(text)
                st.session_state["_raw_parsed"] = parsed
                st.session_state["_raw_parsed_key"] = cache_key
            except Exception as e:
                st.error(f"Could not parse file: {e}")
                st.session_state.pop("_raw_parsed", None)
                st.session_state.pop("_raw_parsed_key", None)
        if "_raw_parsed" in st.session_state:
            papers_ref = st.session_state["_raw_parsed"]
            n_total = len(papers_ref)
            n_abstract = sum(1 for p in papers_ref if p["abstract"])
            st.caption(f"{n_total} papers found - {n_abstract} with abstracts, {n_total - n_abstract} without.")
            if n_total > 0 and st.button("Save to Papers (formatted)", key="load_ref"):
                _dl = _papers_to_csv_bytes(papers_ref)
                st.session_state["step1_papers"] = papers_ref
                st.session_state["s1_file"] = ("papers.csv", _dl)
                _clear_downstream_papers()
                st.session_state["_dl_papers"] = _dl
                st.rerun()
with st.expander("1.2  Extract the embeddings", expanded=False):
    st.caption(
        "Takes the formatted papers file and generates an embeddings file - "
        "one row per paper with an ID and 768 numerical values."
    )
    st.markdown("**Option A - Run on this page** (slower)")
    st.caption("**Reads:** Papers (formatted) - **Saves to Files panel:** Embeddings")
    if "step1_papers" not in st.session_state:
        st.info("No papers loaded. Upload **Papers (formatted)** in the Files panel at the bottom of the page.")
    else:
        st.caption(f"{len(st.session_state['step1_papers'])} papers loaded.")
        ignore_incomplete = st.checkbox(
            "Ignore documents without title or abstract", value=True, key="s1_ignore_incomplete"
        )
        if _mem_caption:
            st.caption(_mem_caption)
        s1_run = st.button("Run Embeddings", key="run_embed", disabled=_is_running)
        if s1_run:
            from pipeline.embed import embed_papers
            papers = st.session_state["step1_papers"]
            if ignore_incomplete:
                papers = [p for p in papers if p.get("title", "").strip() and p.get("abstract", "").strip()]
            st.session_state["running"] = True
            prog = st.progress(0, text="Loading SPECTER2 model...")
            def _cb(cur, tot):
                prog.progress(cur / tot, text=f"Encoding {cur}/{tot}")
            try:
                embeddings = embed_papers(papers, progress_callback=_cb)
                prog.progress(1.0, text="Done.")
                ids = [p["id"] for p in papers]
                st.session_state["step1_embeddings"] = embeddings
                st.session_state["step1_embed_ids"] = ids
            finally:
                st.session_state["running"] = False
            _clear_downstream_embeddings()
            st.session_state["_dl_embeddings"] = array_to_csv_bytes(embeddings, ids=ids)
            st.rerun()
        if "step1_embeddings" in st.session_state:
            show_array_info(st.session_state["step1_embeddings"], "Saved to Files panel")
    st.divider()
    st.markdown("**Option B - Run on Google Colab** (faster, requires moving files manually)")
    st.caption(
        "Open the notebook in Google Colab, set the runtime to **T4 GPU**, and run the cells. "
        "Upload your **Papers (formatted)** CSV when prompted. "
        "When done, upload the resulting `embeddings.csv` to **Embeddings** in the Files panel below."
    )
    st.link_button(
        "Open in Google Colab",
        "https://colab.research.google.com/github/jpbascur/snipets/blob/main/generate_embeddings.ipynb",
        use_container_width=True,
    )
with st.expander("2A.1  Create network", expanded=False):
    st.caption("**Reads:** Embeddings - **Saves to Files panel:** Paper network")
    st.caption(
        "Builds a cosine similarity network - each paper connects to its most similar papers. "
        "Emulates the citation-based approach used in bibliometrics."
    )
    has_embeddings = "step1_embeddings" in st.session_state
    if not has_embeddings:
        st.info("No embeddings loaded. Upload **Embeddings** in the Files panel at the bottom of the page.")
    else:
        embed_src = st.session_state["step1_embeddings"]
        n_papers = len(embed_src)
        c1, c2 = st.columns(2)
        c1.caption("A document connects to its most similar documents. Higher values produce a denser network.")
        top_k = c1.number_input(
            "Maximum number of connections per document",
            min_value=1, max_value=n_papers - 1, value=20, step=1, key="top_k",
        )
        c2.caption("Minimum similarity required to keep a connection. Higher values produce a sparser network.")
        min_sim = c2.slider("Min similarity", 0.0, 1.0, 0.0, 0.01, key="min_sim")
        s2_run = st.button("Build Network", key="run_network", disabled=_is_running)
        if s2_run:
            from pipeline.network import build_edge_list
            st.session_state["running"] = True
            prog = st.progress(0, text="Building edge list")
            def _cb_net(cur, tot):
                prog.progress(cur / tot, text=f"Processing {cur}/{tot} papers")
            try:
                with st.spinner("Computing cosine similarities..."):
                    edges = build_edge_list(
                        embed_src, top_k=int(top_k),
                        min_similarity=float(min_sim), progress_callback=_cb_net,
                    )
                prog.progress(1.0, text="Done.")
                st.session_state["step2_edges"] = edges
            finally:
                st.session_state["running"] = False
            _clear_downstream_edges()
            st.session_state["_dl_edges"] = _edges_to_csv_bytes(edges)
            st.rerun()
        if "step2_edges" in st.session_state:
            st.caption(f"Saved to Files panel - {len(st.session_state['step2_edges'])} edges.")
with st.expander("2A.2  Generate network VOSviewer map", expanded=False):
    st.caption(
        "**Reads:** Paper network + Papers (formatted) - **Saves to Files panel:** Paper network VOSviewer"
    )
    st.caption("Exports the network to VOSviewer format for visualization.")
    has_edges = "step2_edges" in st.session_state
    has_papers = "step1_papers" in st.session_state
    missing = []
    if not has_edges:
        missing.append("Paper network")
    if not has_papers:
        missing.append("Papers (formatted)")
    if missing:
        st.info(f"Missing: {', '.join(missing)}. Upload them in the Files panel at the bottom of the page.")
    else:
        edges_src = st.session_state["step2_edges"]
        papers_src = st.session_state["step1_papers"]
        has_vos_json = "vos_json_auto" in st.session_state
        do_cluster = st.checkbox(
            "Open and cluster (may be slow in dense networks)",
            key="vos_do_cluster", value=True, disabled=not has_vos_json,
        )
        s3_run = st.button("Generate VOSviewer Map", key="run_vos", disabled=_is_running)
        if s3_run:
            with st.spinner("Generating VOSviewer map..."):
                items = [
                    {
                        "id": str(idx + 1),
                        "label": paper.get("title", paper.get("id", str(idx + 1))),
                        "description": str(paper.get("id", "")),
                    }
                    for idx, paper in enumerate(papers_src)
                ]
                items_no_cluster = [{**item, "cluster": 1} for item in items]
                links = [
                    {"source_id": str(i + 1), "target_id": str(j + 1), "strength": round(w, 6)}
                    for i, j, w in edges_src
                ]
                sid = st.session_state["session_id"]
                vos_data_auto  = {"network": {"items": items,            "links": links}}
                vos_data_fixed = {"network": {"items": items_no_cluster, "links": links}}
                st.session_state["vos_json_auto"]      = json.dumps(vos_data_auto,  indent=2)
                st.session_state["vos_json_fixed"]     = json.dumps(vos_data_fixed, indent=2)
                st.session_state["vos_json_url_auto"]  = _write_static_json(f"{sid}_network_auto.json",  vos_data_auto)
                st.session_state["vos_json_url_fixed"] = _write_static_json(f"{sid}_network_fixed.json", vos_data_fixed)
            st.rerun()
        has_vos_json = "vos_json_auto" in st.session_state
        if has_vos_json:
            st.caption("Saved to Files panel - Paper network VOSviewer.")
        vos_json_url = st.session_state.get("vos_json_url_auto" if do_cluster else "vos_json_url_fixed")
        vos_url = _vosviewer_url(vos_json_url, max_n_links=0) if has_vos_json else None
        if has_vos_json and vos_url is None:
            st.caption("Direct opening needs a public app URL. Download the JSON and upload it in VOSviewer Online.")
        st.link_button(
            "Open in VOSviewer Online", vos_url or "https://app.vosviewer.com/",
            type="primary", use_container_width=True, disabled=not has_vos_json or vos_url is None,
        )
with st.expander("2B.1  Generate 2D coordinates", expanded=False):
    st.caption("**Reads:** Embeddings - **Saves to Files panel:** Paper coordinates")
    st.caption(
        "Projects embeddings into 2D space using UMAP - more faithful to the semantic structure "
        "than a network map. Similar papers end up close together; dissimilar ones far apart."
    )
    has_embeddings_umap = "step1_embeddings" in st.session_state
    if not has_embeddings_umap:
        st.info("No embeddings loaded. Upload **Embeddings** in the Files panel at the bottom of the page.")
    else:
        viz_embed_src = st.session_state["step1_embeddings"]
        if "step1_embed_ids" in st.session_state:
            viz_embed_ids = st.session_state["step1_embed_ids"]
        elif "step1_papers" in st.session_state:
            viz_embed_ids = [p["id"] for p in st.session_state["step1_papers"]]
        else:
            viz_embed_ids = [str(i) for i in range(len(viz_embed_src))]
        c1, c2 = st.columns(2)
        c1.caption(
            "Number of documents to consider at a time when preserving the embedding space structure. "
            "Low values keep local structure, high values keep global structure."
        )
        umap_n_neighbors = c1.number_input("n_neighbors", min_value=2, value=15, step=1, key="umap_n_neighbors")
        c2.caption(
            "Minimum distance between documents in the 2D projection. "
            "Low values place similar documents into tight clumps, high values spread them more uniformly."
        )
        umap_min_dist = c2.slider("min_dist", 0.0, 1.0, 0.1, 0.01, key="umap_min_dist")
        n = len(viz_embed_src)
        estimate = "a few seconds" if n < 500 else "~30 seconds" if n < 2000 else "a few minutes"
        st.caption(f"Expected time: {estimate} ({n} papers)")
        sa_run = st.button("Run UMAP", key="run_umap", disabled=_is_running)
        if sa_run:
            from pipeline.reduce import umap_reduce
            st.session_state["running"] = True
            try:
                with st.spinner(f"Running UMAP on {n} papers... ({estimate})"):
                    coords = umap_reduce(
                        viz_embed_src,
                        n_neighbors=int(umap_n_neighbors),
                        min_dist=float(umap_min_dist),
                    )
                st.session_state["viz_coords"] = coords
                st.session_state["viz_ids"]    = viz_embed_ids
            finally:
                st.session_state["running"] = False
            _clear_downstream_coords()
            st.session_state["_dl_coords"] = _coords_to_csv_bytes(viz_embed_ids, coords)
            st.rerun()
        if "viz_coords" in st.session_state:
            st.caption(f"Saved to Files panel - {len(st.session_state['viz_coords'])} points.")
with st.expander("2B.2  Generate coordinates VOSviewer map", expanded=False):
    st.caption(
        "**Reads:** Paper coordinates + Papers (formatted) - **Saves to Files panel:** Paper coordinates VOSviewer"
    )
    st.caption("Exports the UMAP coordinates to VOSviewer format, positioning nodes according to the projection.")
    has_coords = "viz_coords" in st.session_state
    has_papers_vos = "step1_papers" in st.session_state
    missing = []
    if not has_coords:
        missing.append("Paper coordinates")
    if not has_papers_vos:
        missing.append("Papers (formatted)")
    if missing:
        st.info(f"Missing: {', '.join(missing)}. Upload them in the Files panel at the bottom of the page.")
    else:
        vos_coords     = st.session_state["viz_coords"]
        vos_coord_ids  = st.session_state["viz_ids"]
        vos_map_papers = st.session_state["step1_papers"]
        sc_run = st.button("Generate VOSviewer Map", key="run_vos_map", disabled=_is_running)
        if sc_run:
            with st.spinner("Generating VOSviewer map..."):
                coord_lookup = {
                    pid: (float(x), float(y))
                    for pid, (x, y) in zip(vos_coord_ids, vos_coords)
                }
                items = []
                for idx, paper in enumerate(vos_map_papers):
                    pid   = str(paper.get("id", idx + 1))
                    label = paper.get("title", pid)
                    x, y  = coord_lookup.get(pid, (0.0, 0.0))
                    items.append({
                        "id": str(idx + 1), "label": label, "description": pid,
                        "x": round(x, 6), "y": round(y, 6), "cluster": 1,
                    })
                vos_data = {"network": {"items": items, "links": []}}
                sid = st.session_state["session_id"]
                url = _write_static_json(f"{sid}_umap.json", vos_data)
                st.session_state["viz_vos_json"]     = json.dumps(vos_data, indent=2)
                st.session_state["viz_vos_json_url"] = url
            st.rerun()
        has_viz_vos = "viz_vos_json" in st.session_state
        if has_viz_vos:
            st.caption("Saved to Files panel - Paper coordinates VOSviewer.")
        viz_vos_url = _vosviewer_url(st.session_state.get("viz_vos_json_url")) if has_viz_vos else None
        if has_viz_vos and viz_vos_url is None:
            st.caption("Direct opening needs a public app URL. Download the JSON and upload it in VOSviewer Online.")
        st.link_button(
            "Open in VOSviewer Online", viz_vos_url or "https://app.vosviewer.com/",
            type="primary", use_container_width=True, disabled=not has_viz_vos or viz_vos_url is None,
        )
# Files panel
st.divider()
st.subheader("Files")
st.caption("All files in your current session. Upload or download any file here.")
def _file_slot_state(slot_key: str) -> tuple[bool, str, bytes, str, str]:
    if slot_key == "raw":
        loaded = "raw_file" in st.session_state
        filename = st.session_state["raw_file"][0] if loaded else "export"
        data = st.session_state["raw_file"][1] if loaded else b""
        return loaded, filename if loaded else "-", data, filename, "application/octet-stream"
    if slot_key == "papers":
        loaded = "step1_papers" in st.session_state
        status = f"{len(st.session_state['step1_papers'])} papers" if loaded else "-"
        return loaded, status, st.session_state.get("_dl_papers", b""), "papers.csv", "text/csv"
    if slot_key == "embeddings":
        loaded = "step1_embeddings" in st.session_state
        status = (
            f"{st.session_state['step1_embeddings'].shape[0]} x {st.session_state['step1_embeddings'].shape[1]}"
            if loaded else "-"
        )
        return loaded, status, st.session_state.get("_dl_embeddings", b""), "embeddings.csv", "text/csv"
    if slot_key == "edges":
        loaded = "step2_edges" in st.session_state
        status = f"{len(st.session_state['step2_edges'])} edges" if loaded else "-"
        return loaded, status, st.session_state.get("_dl_edges", b""), "network.csv", "text/csv"
    if slot_key == "network_vos":
        loaded = "vos_json_auto" in st.session_state
        data = st.session_state["vos_json_auto"].encode() if loaded else b""
        return loaded, "Ready" if loaded else "-", data, "vosviewer_network.json", "application/json"
    if slot_key == "coords":
        loaded = "viz_coords" in st.session_state
        status = f"{len(st.session_state['viz_coords'])} points" if loaded else "-"
        return loaded, status, st.session_state.get("_dl_coords", b""), "coords.csv", "text/csv"
    if slot_key == "coords_vos":
        loaded = "viz_vos_json" in st.session_state
        data = st.session_state["viz_vos_json"].encode() if loaded else b""
        return loaded, "Ready" if loaded else "-", data, "vosviewer_umap.json", "application/json"
    raise ValueError(f"Unknown file slot: {slot_key}")
_FILE_SLOTS = [
    ("raw", "Papers (unformatted)", "dl_panel_raw_new", "ul_panel_raw", ["txt", "nbib", "ris", "bib"]),
    ("papers", "Papers (formatted)", "dl_panel_papers_new", "ul_panel_papers", ["csv"]),
    ("embeddings", "Embeddings", "dl_panel_embed_new", "ul_panel_embed", ["csv"]),
    ("edges", "Paper network", "dl_panel_edges_new", "ul_panel_edges", ["csv"]),
    ("network_vos", "Paper network VOSviewer", "dl_panel_net_vos_new", "ul_panel_net_vos", ["json"]),
    ("coords", "Paper coordinates", "dl_panel_coords_new", "ul_panel_coords", ["csv"]),
    ("coords_vos", "Paper coordinates VOSviewer", "dl_panel_coords_vos_new", "ul_panel_coords_vos", ["json"]),
]
with st.container(border=True):
    for i, (slot_key, label, dl_key, ul_key, ul_types) in enumerate(_FILE_SLOTS):
        loaded, status, dl_data, dl_fn, dl_mime = _file_slot_state(slot_key)
        col_label, col_dl, col_ul = st.columns([4.5, 1.2, 2.6])
        with col_label:
            st.markdown(f"**{label}**")
            st.caption(status)
        with col_dl:
            st.download_button(
                "Download", dl_data, dl_fn, mime=dl_mime,
                key=dl_key, disabled=not loaded, use_container_width=True,
            )
        with col_ul:
            st.file_uploader(
                "Upload",
                type=ul_types,
                key=ul_key,
                accept_multiple_files=False,
                on_change=handle_panel_upload,
                args=(ul_key, slot_key),
                label_visibility="collapsed",
            )
            upload_error = st.session_state.get(f"_upload_error_{ul_key}")
            if upload_error:
                st.error(upload_error)
        if i < len(_FILE_SLOTS) - 1:
            st.divider()
